let stockProductos = [
    {id: 1, nombre: "Bombilla1", tipo: "bombilla", cantidad: 1, desc: "Bombilla de acero inoxidable", precio: 1200, img: './img/bombilla1.jpg'},
    {id: 2, nombre: "Bombilla2", tipo: 1, cantidad: 1, desc: "Bombilla de acero inoxidable", precio: 1100, img: './img/bombilla2.jpg'},
    {id: 3, nombre: "Bombilla3", tipo: 1, cantidad: 1, desc: "Bombilla de acero inoxidable", precio: 1200, img: './img/bombilla3.jpg'},
    {id: 4, nombre: "Bombilla4", tipo: 1, cantidad: 1, desc: "Bombilla de acero inoxidable", precio: 1400, img: './img/bombilla2.jpg'},
    {id: 5, nombre: "Bombilla5", tipo: 1, cantidad: 1, desc: "Bombilla de acero inoxidable", precio: 1200, img: './img/bombilla1.jpg'},
    {id: 6, nombre: "Bombilla6", tipo: 1, cantidad: 1, desc: "Bombilla de acero inoxidable", precio: 1500, img: './img/bombilla3.jpg'},
    {id: 7, nombre: "mate 1", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 500, img: './img/mate1.jpg'},
    {id: 8, nombre: "mate 2", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 500, img: './img/mate2.jpg'},
    {id: 9, nombre: "mate 3", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 500,img: './img/mate3.jpg'},
    {id: 10, nombre: "mate 4", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 700, img: './img/mate4.jpg'},
    {id: 11, nombre: "mate 5", tipo: 2, cantidad: 1,desc: "Un Mate bien nuestro", precio: 700, img: './img/mate1.jpg'},
    {id: 12, nombre: "mate 6", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 700, img: './img/mate2.jpg'},
    {id: 13, nombre: "mate 7", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 900, img: './img/mate3.jpg'},
    {id: 14, nombre: "mate 8", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 1400, img: './img/mate4.jpg'},
    {id: 15, nombre: "mate 9", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 4000, img: './img/mate1.jpg'},
    {id: 16, nombre: "mate 10", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 2000, img: './img/mate2.jpg'},
    {id: 17, nombre: "mate 11", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 2300, img: './img/mate3.jpg'},
    {id: 18, nombre: "mate 12", tipo: 2, cantidad: 1, desc: "Un Mate bien nuestro", precio: 1600, img: './img/mate4.jpg'},
    {id: 19, nombre: "Cuchillo 1", tipo: 3, cantidad: 1, desc: "El filo de tus asados", precio: 3000, img: './img/cu1.jpg'},
    {id: 20, nombre: "Cuchillo 2", tipo: 3, cantidad: 1, desc: "El filo de tus asados", precio: 2500, img: './img/cu2.jpg'},
    {id: 21, nombre: "Cuchillo 3", tipo: 3, cantidad: 1, desc: "El filo de tus asados", precio: 2350, img: './img/cu3.jpg'},
]

